Repository Kong/sdk-portal-js, pull requests merged in 2024-02, with the labels that each got.

#84 chore: generate-sdk.yaml
  .github/workflows/generate-sdk.yaml
Labels: skip-release

#80 Automated OAS Update
  openapi.yaml
  src/api.ts
Labels: minor

#86 Automated OAS Update
  openapi.yaml
  src/api.ts
Labels: minor

#89 chore(deps): update auto version
  package.json
  yarn.lock
Labels: dependencies
